name: MobCapturer
version: ${project.version}
author: plleg
description: A Slimefun Addon that adds a tool that allows you to capture mobs
website: https://github.com/plleg/MobCapturer

main: me.plleg.mobcapturer.MobCapturer
depend: [Slimefun]

api-version: 1.19
